version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: lockfile-only
    open-pull-requests-limit: 10
    commit-message:
      prefix: "Composer"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: lockfile-only
    open-pull-requests-limit: 10
    commit-message:
      prefix: "npm"
    allow:
      - dependency-type: "all"
