name: Release

on:
    push:
        tags:
            - '*.*.*'

env:
    PLUGIN_SLUG: wp-feature-notifications

jobs:
    release:
        name: Create Release
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: ./.github/actions/node

            - name: Build package
              shell: bash
              run: npm run build --if-present

            - name: Create artifacts
              shell: bash
              run: rsync -rc --exclude-from="${GITHUB_WORKSPACE}/.distignore" "${GITHUB_WORKSPACE}/" "${PLUGIN_SLUG}/" --delete --delete-excluded && zip -r "${GITHUB_WORKSPACE}/${PLUGIN_SLUG}.zip" "${PLUGIN_SLUG}"
